# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=toy
    volumes:
      - mysql-data-toys:/var/lib/mysql
      - ./toys.sql/docker-entrypoint-initdb.d/init.sql

  web:
    image: toystore:latest
    ports:
      - "8005:8080"
    depends_on:
      - mysql